; PlatformIO Project Configuration for DUCO Miner on CH32V003

[platformio]
default_envs =
    ch32v003f4p6_evt_r0
    genericCH32V003F4P6
    genericCH32V003A4M6
    genericCH32V003J4M6
    genericCH32V003F4U6

[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = noneos
build_flags =
    -Wall
    -DCH32V003
    -Ofast
src_dir = .
build_src_filter =
    +<*>
    -<.git/>
    -<.pio/>
    -<build/>
    -<*.md>
monitor_speed = 115200
upload_protocol = wch-link

[env:ch32v003f4p6_evt_r0]
board = ch32v003f4p6_evt_r0

[env:genericCH32V003F4P6]
board = genericCH32V003F4P6

[env:genericCH32V003A4M6]
board = genericCH32V003F4P6   ; dùng chung định nghĩa board (cùng chip)

[env:genericCH32V003J4M6]
board = genericCH32V003F4P6

[env:genericCH32V003F4U6]
board = genericCH32V003F4U6
