; PlatformIO Project Configuration for DUCO Miner on CH32V003

[platformio]
default_envs =
    ch32v003f4p6_evt_r0
    genericCH32V003F4P6
    genericCH32V003A4M6
    genericCH32V003J4M6
    genericCH32V003F4U6

[env]
platform = https://github.com/Community-PIO-CH32V/platform-ch32v.git
framework = arduino
build_flags =
    -Wall
    -DCH32V003
    -Ofast
    -Ilib/ch32fun/ch32v003fun
src_dir = .
monitor_speed = 115200
upload_protocol = wch-link
build_src_filter =
    +<*>
    -<.git/>
    -<.pio/>
    -<build/>
    -<*.md>
    -<framework-arduino-openwch-ch32/cores/arduino/main.cpp>

[env:ch32v003f4p6_evt_r0]
board = ch32v003f4p6_evt_r0

[env:genericCH32V003F4P6]
board = genericCH32V003F4P6

[env:genericCH32V003A4M6]
board = genericCH32V003F4P6

[env:genericCH32V003J4M6]
board = genericCH32V003F4P6

[env:genericCH32V003F4U6]
board = genericCH32V003F4U6
